# Procesamiento de imágenes de perros y gatos

1. Explorar las imágenes de gatos y perros y guardar sus rutas
2. Abrir las imágenes y normalizarlas a escala de grises, centradas de 28x28 pixeles
3. Guardar las imágenes normalizadas como `cat_0.png`, `cat_1.png`, ..., `cat_12499.png` y lo mismo para `dog_0.png`, `dog_1.png`, ..., `dog_12499.png`

In [1]:
import pandas

import os
import re

In [2]:
cats = []

for root, subs, files in os.walk("../../Cat"):
    for file in files:
        for match in re.finditer(r"(\d+)\.jpg", file):
            id = int(match.group(1))
            # print(file, id)
            cats.append((id, file))

cats = pandas.DataFrame(cats, columns=["ID", "PATH"])

cats["TYPE"] = "Cat"

cats = cats.sort_values("ID").reset_index().drop("index", axis=1)

cats

          ID       PATH TYPE
0          0      0.jpg  Cat
1          1      1.jpg  Cat
2          2      2.jpg  Cat
3          3      3.jpg  Cat
4          4      4.jpg  Cat
...      ...        ...  ...
12494  12495  12495.jpg  Cat
12495  12496  12496.jpg  Cat
12496  12497  12497.jpg  Cat
12497  12498  12498.jpg  Cat
12498  12499  12499.jpg  Cat

[12499 rows x 3 columns]

In [3]:
dogs = []

for root, subs, files in os.walk("../../Dog"):
    for file in files:
        for match in re.finditer(r"(\d+)\.jpg", file):
            id = int(match.group(1))
            # print(file, id)
            dogs.append((id, file))

dogs = pandas.DataFrame(dogs, columns=["ID", "PATH"])

dogs["TYPE"] = "Dog"

dogs = dogs.sort_values("ID").reset_index().drop("index", axis=1)

dogs

          ID       PATH TYPE
0          0      0.jpg  Dog
1          1      1.jpg  Dog
2          2      2.jpg  Dog
3          3      3.jpg  Dog
4          4      4.jpg  Dog
...      ...        ...  ...
12495  12495  12495.jpg  Dog
12496  12496  12496.jpg  Dog
12497  12497  12497.jpg  Dog
12498  12498  12498.jpg  Dog
12499  12499  12499.jpg  Dog

[12500 rows x 3 columns]

In [4]:
catdogs = pandas.concat([cats, dogs]).reset_index().drop("index", axis=1)

catdogs

          ID       PATH TYPE
0          0      0.jpg  Cat
1          1      1.jpg  Cat
2          2      2.jpg  Cat
3          3      3.jpg  Cat
4          4      4.jpg  Cat
...      ...        ...  ...
24994  12495  12495.jpg  Dog
24995  12496  12496.jpg  Dog
24996  12497  12497.jpg  Dog
24997  12498  12498.jpg  Dog
24998  12499  12499.jpg  Dog

[24999 rows x 3 columns]

In [ ]:
from PIL import Image
import numpy

# from matplotlib import pyplot

# figure, axes = pyplot.subplots(1, 2, figsize=(10, 10))

correctas = []

for (index, id, path, type) in catdogs.itertuples():
    if index % 1000 == 0:
        print(index, id, path, type)

    try:
        image = Image.open(f"../../{type}/{path}")
        image = image.convert("L")
        image = numpy.ascontiguousarray(image)

        height, width = image.shape

        L = max(width, height)
        dx = L - width
        dy = L - height

        # print(width, height, L, dx, dy)

        image2 = numpy.zeros((L, L)) + 255

        image2[int(dy/2):int(dy/2)+height, int(dx/2):int(dx/2)+width] = image

        # axes[0].imshow(255 - image, cmap="Grays")
        # axes[1].imshow(255 - image2, cmap="Grays")

        Image.fromarray(image2).resize((64, 64)).convert("RGB").save(f"../../catdogs/{type}_{id}.png")

        correctas.append((id, type, f"../../catdogs/{type}_{id}.png", f"../../{type}/{path}"))
    except Exception as e:
        print("ERROR:", id)

    # break

# pyplot.show()

correctas = pandas.DataFrame(correctas, columns=["ID", "TYPE", "PATH", "ORIGINAL_PATH"])

correctas.to_csv("catdogs.csv", index=False)

correctas

0 0 0.jpg Cat
1000 1001 1001.jpg Cat
2000 2001 2001.jpg Cat
3000 3001 3001.jpg Cat
4000 4001 4001.jpg Cat
5000 5001 5001.jpg Cat
6000 6001 6001.jpg Cat
7000 7001 7001.jpg Cat
8000 8001 8001.jpg Cat
9000 9001 9001.jpg Cat
10000 10001 10001.jpg Cat
11000 11001 11001.jpg Cat
12000 12001 12001.jpg Cat
13000 501 501.jpg Dog
14000 1501 1501.jpg Dog
15000 2501 2501.jpg Dog
16000 3501 3501.jpg Dog
17000 4501 4501.jpg Dog
18000 5501 5501.jpg Dog
19000 6501 6501.jpg Dog
20000 7501 7501.jpg Dog
21000 8501 8501.jpg Dog

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/PIL/TiffImagePlugin.py:900: UserWarning: Truncated File Read
  warnings.warn(str(msg))

22000 9501 9501.jpg Dog
23000 10501 10501.jpg Dog
24000 11501 11501.jpg Dog
ERROR: 11702

          ID TYPE                         PATH        ORIGINAL_PATH
0          0  Cat      ../../catdogs/Cat_0.png      ../../Cat/0.jpg
1          1  Cat      ../../catdogs/Cat_1.png      ../../Cat/1.jpg
2          2  Cat      ../../catdogs/Cat_2.png      ../../Cat/2.jpg
3          3  Cat      ../../catdogs/Cat_3.png      ../../Cat/3.jpg
4          4  Cat      ../../catdogs/Cat_4.png      ../../Cat/4.jpg
...      ...  ...                          ...                  ...
24993  12495  Dog  ../../catdogs/Dog_12495.png  ../../Dog/12495.jpg
24994  12496  Dog  ../../catdogs/Dog_12496.png  ../../Dog/12496.jpg
24995  12497  Dog  ../../catdogs/Dog_12497.png  ../../Dog/12497.jpg
24996  12498  Dog  ../../catdogs/Dog_12498.png  ../../Dog/12498.jpg
24997  12499  Dog  ../../catdogs/Dog_12499.png  ../../Dog/12499.jpg

[24998 rows x 4 columns]