In [1]:
import pandas
import numpy
from matplotlib import pyplot
import seaborn

from PIL import Image

In [2]:
catdogs = pandas.read_csv("catdogs.csv")

catdogs

          ID TYPE                         PATH        ORIGINAL_PATH
0          0  Cat      ../../catdogs/Cat_0.png      ../../Cat/0.jpg
1          1  Cat      ../../catdogs/Cat_1.png      ../../Cat/1.jpg
2          2  Cat      ../../catdogs/Cat_2.png      ../../Cat/2.jpg
3          3  Cat      ../../catdogs/Cat_3.png      ../../Cat/3.jpg
4          4  Cat      ../../catdogs/Cat_4.png      ../../Cat/4.jpg
...      ...  ...                          ...                  ...
24993  12495  Dog  ../../catdogs/Dog_12495.png  ../../Dog/12495.jpg
24994  12496  Dog  ../../catdogs/Dog_12496.png  ../../Dog/12496.jpg
24995  12497  Dog  ../../catdogs/Dog_12497.png  ../../Dog/12497.jpg
24996  12498  Dog  ../../catdogs/Dog_12498.png  ../../Dog/12498.jpg
24997  12499  Dog  ../../catdogs/Dog_12499.png  ../../Dog/12499.jpg

[24998 rows x 4 columns]

In [52]:
catdogs["PATH"]

0            ../../catdogs/Cat_0.png
1            ../../catdogs/Cat_1.png
2            ../../catdogs/Cat_2.png
3            ../../catdogs/Cat_3.png
4            ../../catdogs/Cat_4.png
                    ...
24993    ../../catdogs/Dog_12495.png
24994    ../../catdogs/Dog_12496.png
24995    ../../catdogs/Dog_12497.png
24996    ../../catdogs/Dog_12498.png
24997    ../../catdogs/Dog_12499.png
Name: PATH, Length: 24998, dtype: object

In [53]:
X = numpy.vstack(
    catdogs["PATH"].apply(
        lambda path: numpy.ascontiguousarray(Image.open(path).convert("L")).reshape(64 * 64))
        .apply(lambda x: (255 - x) / 255).values)

X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [54]:
catdogs["TYPE"]

0        Cat
1        Cat
2        Cat
3        Cat
4        Cat
        ...
24993    Dog
24994    Dog
24995    Dog
24996    Dog
24997    Dog
Name: TYPE, Length: 24998, dtype: object

In [9]:
y1 = (catdogs["TYPE"] == "Cat").astype(int)
y2 = (catdogs["TYPE"] == "Dog").astype(int)

Y = pandas.DataFrame({
    "y1": y1,
    "y2": y2,
})

Y

       y1  y2
0       1   0
1       1   0
2       1   0
3       1   0
4       1   0
...    ..  ..
24993   0   1
24994   0   1
24995   0   1
24996   0   1
24997   0   1

[24998 rows x 2 columns]

In [56]:
! pip install scikit-learn

WARNING: Ignoring invalid distribution -ensorflow (/Users/dragonnomada/.pyenv/versions/3.10.15/lib/python3.10/site-packages)
Requirement already satisfied: scikit-learn in /Users/dragonnomada/.pyenv/versions/3.10.15/lib/python3.10/site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in /Users/dragonnomada/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.8.0 in /Users/dragonnomada/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in /Users/dragonnomada/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/dragonnomada/.pyenv/versions/3.10.15/lib/python3.10/site-packages (from scikit-learn) (3.6.0)
WARNING: Ignoring invalid distribution -ensorflow (/Users/dragonnomada/.pyenv/versions/3.10.15/lib/python3.10/site-packages)
WARNING: Ignoring invalid distribution -ensorflow (/Users/dragonnomada/.pyenv/versions/3.10.15/lib/python3.10/site-packages)

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [57]:
from sklearn.model_selection import train_test_split

Xa, Xb, Ya, Yb = train_test_split(X, Y, test_size=3000, random_state=123)

In [58]:
Xa

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [59]:
import keras

modelo = keras.Sequential([
    keras.Input(shape=(64 * 64,)),
    keras.layers.Dense(128, activation="relu"),
    keras.layers.Dense(128, activation="relu"),
    keras.layers.Dense(2, activation="sigmoid"),
])

modelo.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 128)            │       524,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 128)            │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 2)              │           258 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 541,186 (2.06 MB)

 Trainable params: 541,186 (2.06 MB)

 Non-trainable params: 0 (0.00 B)

In [60]:
modelo.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

In [61]:
historial = modelo.fit(Xa, Ya, epochs=100)

Epoch 1/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.5505 - loss: 0.7021
Epoch 2/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.5779 - loss: 0.6784
Epoch 3/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.5937 - loss: 0.6692
Epoch 4/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.5942 - loss: 0.6677
Epoch 5/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6078 - loss: 0.6595
Epoch 6/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6076 - loss: 0.6595
Epoch 7/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6022 - loss: 0.6622
Epoch 8/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6124 - loss: 0.6551
Epoch 9/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6113 - loss: 0.6570
Epoch 10/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6107 - loss: 0.6582
Epoch 11/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6110 - loss: 0.6578
Epoch 12/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.6191 - loss: 0.6494
Epoch 13/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.6183 - loss: 0.6525
Epoch 14/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.6171 - loss: 0.6520
Epoch 15/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.6242 - loss: 0.6460
Epoch 16/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.6176 - loss: 0.6493
Epoch 17/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.6231 - loss: 0.6437
Epoch 18/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6155 - loss: 0.6496
Epoch 19/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6235 - loss: 0.6453
Epoch 20/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6249 - loss: 0.6437
Epoch 21/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6158 - loss: 0.6461
Epoch 22/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6201 - loss: 0.6450
Epoch 23/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6279 - loss: 0.6447
Epoch 24/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6318 - loss: 0.6394
Epoch 25/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6247 - loss: 0.6427
Epoch 26/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6324 - loss: 0.6381
Epoch 27/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6367 - loss: 0.6349
Epoch 28/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6351 - loss: 0.6367
Epoch 29/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6330 - loss: 0.6346
Epoch 30/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6318 - loss: 0.6363
Epoch 31/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6317 - loss: 0.6346
Epoch 32/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6331 - loss: 0.6366
Epoch 33/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6373 - loss: 0.6319
Epoch 34/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6400 - loss: 0.6297
Epoch 35/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6315 - loss: 0.6352
Epoch 36/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6368 - loss: 0.6341
Epoch 37/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6356 - loss: 0.6311
Epoch 38/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6385 - loss: 0.6283
Epoch 39/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6392 - loss: 0.6298
Epoch 40/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6417 - loss: 0.6290
Epoch 41/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6467 - loss: 0.6265
Epoch 42/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6388 - loss: 0.6284
Epoch 43/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6361 - loss: 0.6281
Epoch 44/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6432 - loss: 0.6252
Epoch 45/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6346 - loss: 0.6296
Epoch 46/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6414 - loss: 0.6275
Epoch 47/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6455 - loss: 0.6214
Epoch 48/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.6459 - loss: 0.6270
Epoch 49/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6474 - loss: 0.6234
Epoch 50/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6469 - loss: 0.6237
Epoch 51/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6483 - loss: 0.6218
Epoch 52/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6463 - loss: 0.6232
Epoch 53/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6490 - loss: 0.6182
Epoch 54/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6534 - loss: 0.6177
Epoch 55/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6530 - loss: 0.6186
Epoch 56/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6429 - loss: 0.6199
Epoch 57/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6572 - loss: 0.6112
Epoch 58/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6488 - loss: 0.6184
Epoch 59/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6527 - loss: 0.6132
Epoch 60/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6496 - loss: 0.6156
Epoch 61/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6520 - loss: 0.6171
Epoch 62/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6561 - loss: 0.6134
Epoch 63/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6572 - loss: 0.6119
Epoch 64/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6534 - loss: 0.6160
Epoch 65/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6620 - loss: 0.6067
Epoch 66/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6571 - loss: 0.6087
Epoch 67/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6589 - loss: 0.6082
Epoch 68/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6614 - loss: 0.6063
Epoch 69/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6512 - loss: 0.6133
Epoch 70/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6654 - loss: 0.6010
Epoch 71/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6569 - loss: 0.6071
Epoch 72/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6593 - loss: 0.6080
Epoch 73/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6555 - loss: 0.6072
Epoch 74/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6630 - loss: 0.6034
Epoch 75/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6648 - loss: 0.6042
Epoch 76/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6577 - loss: 0.6055
Epoch 77/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6559 - loss: 0.6089
Epoch 78/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6585 - loss: 0.6043
Epoch 79/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6615 - loss: 0.6065
Epoch 80/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6590 - loss: 0.6061
Epoch 81/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6664 - loss: 0.5984
Epoch 82/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6689 - loss: 0.5989
Epoch 83/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.6687 - loss: 0.5963
Epoch 84/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6655 - loss: 0.6022
Epoch 85/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.6685 - loss: 0.5970
Epoch 86/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6719 - loss: 0.5924
Epoch 87/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6708 - loss: 0.5934
Epoch 88/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6611 - loss: 0.5989
Epoch 89/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6635 - loss: 0.5946
Epoch 90/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6681 - loss: 0.5971
Epoch 91/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6707 - loss: 0.5896
Epoch 92/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6643 - loss: 0.5952
Epoch 93/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6680 - loss: 0.5930
Epoch 94/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6670 - loss: 0.5950
Epoch 95/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6685 - loss: 0.5958
Epoch 96/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6698 - loss: 0.5887
Epoch 97/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6697 - loss: 0.5890
Epoch 98/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6762 - loss: 0.5911
Epoch 99/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6740 - loss: 0.5865
Epoch 100/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6640 - loss: 0.5949

In [63]:
modelo.evaluate(Xb, Yb)

94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6061 - loss: 0.6933

[0.6997601985931396, 0.5973333120346069]

## Entrenamiento con una Red Neuronal Convolucional

In [4]:
import keras

modelo = keras.Sequential([
    keras.Input(shape=(64, 64, 1)),
    keras.layers.Conv2D(32, 5, strides=2, activation="relu"),
    keras.layers.Conv2D(32, 3, strides=2, activation="relu"),
    keras.layers.MaxPool2D(5),
    keras.layers.Flatten(),
    keras.layers.Dense(2, activation="sigmoid"),
])

modelo.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 30, 30, 32)     │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 14, 14, 32)     │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 2, 2, 32)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 2)              │           258 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10,338 (40.38 KB)

 Trainable params: 10,338 (40.38 KB)

 Non-trainable params: 0 (0.00 B)

In [5]:
modelo.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

In [6]:
X = numpy.vstack(
    catdogs["PATH"].apply(
        lambda path: numpy.ascontiguousarray(Image.open(path).convert("L")).reshape(64, 64, 1))
        .apply(lambda x: (255 - x) / 255).values).reshape(len(catdogs["PATH"]), 64, 64, 1)

X

array([[[[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        ...,

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]]],


       [[[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.10588235],
         [0.10588235],
         [0.10588235],
         ...,
         [0.08627451],
         [0.0627451 ],
         [0.03137255]],

        [[0.80784314],
         [0.78823529],
         [0.79215686],
         ...,
         [0.64313725],
         [0.4745098 ],
         [0.23137255]],

        ...,

        [[0.75686275],
         [0.76470588],
         [0.76078431],
         ...,
         [0.61568627],
         [0.65882353],
         [0.7254902 ]],

        [[0.01568627],
         [0.01568627],
         [0.01568627],
         ...,
         [0.01176471],
         [0.01176471],
         [0.01568627]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]]],


       [[[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        ...,

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]]],


       ...,


       [[[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        ...,

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]]],


       [[[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        ...,

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]]],


       [[[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        ...,

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]]]])

In [7]:
X.shape

(24998, 64, 64, 1)

In [10]:
from sklearn.model_selection import train_test_split

Xa, Xb, Ya, Yb = train_test_split(X, Y, test_size=3000, random_state=123)

In [11]:
historial = modelo.fit(Xa, Ya, epochs=35)

Epoch 1/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.5612 - loss: 0.6799
Epoch 2/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.6493 - loss: 0.6294
Epoch 3/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.6771 - loss: 0.6017
Epoch 4/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.6960 - loss: 0.5823
Epoch 5/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7025 - loss: 0.5702
Epoch 6/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.7161 - loss: 0.5569
Epoch 7/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7225 - loss: 0.5456
Epoch 8/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.7279 - loss: 0.5394
Epoch 9/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.7347 - loss: 0.5315
Epoch 10/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.7384 - loss: 0.5239
Epoch 11/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.7467 - loss: 0.5180
Epoch 12/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.7409 - loss: 0.5156
Epoch 13/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.7496 - loss: 0.5059
Epoch 14/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 10s 14ms/step - accuracy: 0.7646 - loss: 0.4901
Epoch 15/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.7585 - loss: 0.4957
Epoch 16/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.7579 - loss: 0.4981
Epoch 17/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.7590 - loss: 0.4907
Epoch 18/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.7665 - loss: 0.4854
Epoch 19/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.7648 - loss: 0.4797
Epoch 20/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.7709 - loss: 0.4746
Epoch 21/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.7772 - loss: 0.4658
Epoch 22/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.7752 - loss: 0.4686
Epoch 23/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7772 - loss: 0.4634
Epoch 24/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7777 - loss: 0.4612
Epoch 25/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7851 - loss: 0.4602
Epoch 26/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7889 - loss: 0.4507
Epoch 27/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7917 - loss: 0.4441
Epoch 28/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7912 - loss: 0.4405
Epoch 29/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7982 - loss: 0.4367
Epoch 30/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7938 - loss: 0.4358
Epoch 31/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.7974 - loss: 0.4313
Epoch 32/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7983 - loss: 0.4323
Epoch 33/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7922 - loss: 0.4357
Epoch 34/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.8016 - loss: 0.4296
Epoch 35/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.8079 - loss: 0.4163

In [13]:
modelo.evaluate(Xb, Yb)

94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7362 - loss: 0.5132

[0.5342577695846558, 0.7323333621025085]

In [12]:
modelo.save("cnn_32_32_64x64x1_35e.keras")